### ISSUE TITLE
Compile doesn't fail on invalid expression

### ISSUE THREAD

**Issue by knksmith57** [zordius/lightncandy#154]
Encountering an issue where compilation is succeeding when it shouldn't.

Given the following template:

```hbs
{{#each someArray}}
  {{@index + 1}}
{{/each}}
```

The JS Handlebars CLI will fail as follows:

```text
$ handlebars template.hbs

/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:150
    throw new Error(str);
          ^
Error: Parse error on line 2:
...eArray}}  {{@index + 1}}{{/each}}
----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'DATA', 'SEP', got 'INVALID'
    at Object.parseError (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:150:11)
    at Object.parse (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:202:22)
    at HandlebarsEnvironment.parse (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:25:30)
    at precompile (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:429:17)
    at HandlebarsEnvironment.hb.precompile (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/dist/cjs/handlebars.js:22:12)
    at processTemplate (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/lib/precompiler.js:106:36)
    at /Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/lib/precompiler.js:131:5
    at Array.forEach (native)
    at Object.module.exports.cli (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/lib/precompiler.js:130:18)
    at Object.<anonymous> (/Users/kbsmith/.nvm/v0.10.36/lib/node_modules/handlebars/bin/handlebars:111:38)
```

While using the following LightnCandy command will succeed:

```sh
$ php compile.php
<?php return function ($in, $debugopt = 1) {
    $cx = array(
        'flags' => array(
            'jstrue' => false,
            'jsobj' => false,
            'spvar' => false,
            'prop' => false,
            'method' => false,
            'mustlok' => false,
            'echo' => true,
            'debug' => $debugopt,
        ),
        'constants' => array(),
        'helpers' => array(),
        'blockhelpers' => array(),
        'hbhelpers' => array(),
        'partials' => array(),
        'scopes' => array(),
        'sp_vars' => array('root' => $in),
        'lcrun' => 'LCRun3',

    );

    ob_start();echo '',LCRun3::sec($cx, ((isset($in['someArray']) && is_array($in)) ? $in['someArray'] : null), $in, true, function($cx, $in) {echo '
  ',htmlentities((string)((isset($in['@index']) && is_array($in)) ? $in['@index'] : null), ENT_QUOTES, 'UTF-8'),'
';}),'
';return ob_get_clean();
}
?>
```

```php
// compile.php
<?php

require('src/lightncandy.php');

echo LightnCandy::compile(
  file_get_contents('template.hbs'),
  array(
    'flags' => 0 | LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_ECHO
  )
);
```

As you can see, the output doesn't actually contain the `+ 1`, or the sum of `@index + 1`. It is failing silently and causing a parity issue.

I'm using the latest stable release of LightnCandy with the following software versions:
```txt
$ php --version
PHP 5.3.29 (cli) (built: Jan 28 2015 16:47:43)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

$ handlebars --version
3.0.1
```

**Comment by zordius** [comment]
Thank you for the report , will work on it later.

**Comment by zordius** [comment]
Now an error `Wrong variable naming as 'xxxxxxx' in {{xxxxxxxxxx}} ! You should wrap ! \" # % & ' * + , ; < = > { | } ~ into [ ]` should appear , please try current master, thanks.

**Comment by knksmith57** [comment]
Just to confirm, I am only able to make the test case fail (and ∴ build fail) if the `FLAG_HANDLEBARSJS` option is set.

Is this the expected behavior?

**Comment by zordius** [comment]
Yes, I add extra validation based on this document: http://handlebarsjs.com/expressions.html :

```
Identifiers may be any unicode character except for the following:
Whitespace ! " # % & ' ( ) * + , . / ; < = > @ [ \ ] ^ ` { | } ~
```

And it is for handlebars, but I can not find the validation spec of mustache. So the new validation is only for handlebars.
