### ISSUE TITLE
Error while compiling template with nested subexpression

### ISSUE THREAD

**Issue by MasonM** [zordius/lightncandy#257]
The PHP Code:
-------------

```php
<?php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$template = '{{echo text=(echo text=(echo text="hello"))}}';
$phpStr = LightnCandy::compile($template, [
    'helpers' => [
        'echo' => function ($opts) { return $opts['hash']['text']; },
    ],
    'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS,
]);
$output = eval($phpStr);
echo $output(array());
```

Output:
-------
```
[02-Mar-2017 00:15:22 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unexcepted ')' in expression 'echo text=(echo text=(echo text="hello"))' !!' in /code/vendor/zordius/lightncandy/src/LightnCandy.php:108
Stack trace:
#0 /code/vendor/zordius/lightncandy/src/LightnCandy.php(55): LightnCandy\LightnCandy::handleError(Array)
#1 /code/html/bug.php(12): LightnCandy\LightnCandy::compile('{{echo text=(ec...', Array)
#2 {main}
  thrown in /code/vendor/zordius/lightncandy/src/LightnCandy.php on line 108

Fatal error: Uncaught exception 'Exception' with message 'Unexcepted ')' in expression 'echo text=(echo text=(echo text="hello"))' !!' in /code/vendor/zordius/lightncandy/src/LightnCandy.php:108
Stack trace:
#0 /code/vendor/zordius/lightncandy/src/LightnCandy.php(55): LightnCandy\LightnCandy::handleError(Array)
#1 /code/html/bug.php(12): LightnCandy\LightnCandy::compile('{{echo text=(ec...', Array)
#2 {main}
  thrown in /code/vendor/zordius/lightncandy/src/LightnCandy.php on line 108
```

The Issue:
----------

If you call a helper with a nested subexpression for a named argument, it fails to parse the inner "(". I tracked this down to the `LightnCandy\Parser::analyze()` method. When the outer "(" is parsed, it sets `$expect = ')';` and then hits line 425 (`if ($expect) {`) in the next iteration. Line 427 has a `(substr($t, 0, 1) === '(')` check, which I believe is meant to handle the case of a nested subexpression, but it doesn't work when you have a named argument, because the token will be something like `text=(`.

**Comment by zordius** [comment]
Thank you for reporting this, will fix it later.

**Comment by zordius** [comment]
It should be fixed in current master branch, please try the composer version dev-master or 1.0.4-dev , thanks.
