### ISSUE TITLE
Include partial files

### ISSUE THREAD

**Issue by snoopy4ever** [zordius/lightncandy#312]
Hello there!

I'm not sure if I'm missing something, but I cannot include partials...

So I have my default.hbs file and there I'm trying to include my header:

```hbs
  {{> header }}
```
file is located in ./partials/header.hbs and my config for lightncandy is following:

```php
  'flags'		=> LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_SPVARS | LightnCandy::FLAG_INSTANCE | LightnCandy::FLAG_ERROR_EXCEPTION,
  'hbhelpers'	=> $helpers,
  'basedir' => Array(
    '/views',
    '/views/partials'
  ),
  'fileext'	=> array('.hbs')
```
I've got this error and I'm not sure what I'm doing wrong:

```
Fatal error:  Uncaught Exception: Can not find partial for 'header', you should provide partials or partialresolver in options in \public_html\vendor\lightncandy\LightnCandy.php:113
Stack trace:
#0 \public_html\vendor\lightncandy\LightnCandy.php(55): LightnCandy\LightnCandy::handleError(Array)
#1 \public_html\Core\lightncandy.php(50): LightnCandy\LightnCandy::compile('{{&gt; header }}\r\n...', Array)
#2 \public_html\loader.php(22): require_once('C:\\VirtualDrive...')
#3 \public_html\index.php(7): require_once('C:\\VirtualDrive...')
#4 {main}
  thrown in \public_html\vendor\lightncandy\LightnCandy.php on line 113
```

Please help,

Many thanks in advance.

Peter.

**Comment by zordius** [comment]
From your provided information you should using old version of lightncandy or other frameworks based on lightncandy. for older version document you may check here: https://github.com/zordius/lightncandy/tree/v0.23 .

**Comment by snoopy4ever** [comment]
Hi @zordius,
Thanks for the info, I'm using latest version downloaded from this repo.
C:\\VirtualDrive... path is correct, works with everything else, I had also  mustache here previously and includes were working OK, I will try clean installation for now and will test that, will let you know what are the results of that.
Many thanks,
Peter

**Comment by snoopy4ever** [comment]
I've done clean deploy on my dev box (CentOS 7, PHP 5.6.40) from here: https://github.com/zordius/lightncandy/tree/master/src

This is my folder structure (maybe I'm missing something):

![image](https://user-images.githubusercontent.com/18528628/59697225-66d0a980-91e5-11e9-8595-3390d060e422.png)

In `src` I've got copy of Lightncandy, in cache - cache files, in partials I have header.hbs, content of main.hbs is as follows:

```hbs
{{> header }}

MAIN TEMPLATE {{ test }}
```

Content of my index.php file is:

```php
<?php

require_once( './src/loader.php' );

use LightnCandy\LightnCandy;

$template = file_get_contents( './main.hbs' );

$config_template = array(
  'flags'     => LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_SPVARS | LightnCandy::FLAG_INSTANCE | LightnCandy::FLAG_ERROR_EXCEPTION,
  'basedir'   => Array([
    './',
    './partials'
  ]),
  'fileext'	  => Array([
    '.hbs'
  ])
);

$phpStr = LightnCandy::compile($template, $config_template);

file_put_contents( './cache/cache_' . $cacheName . '.php', '<?php ' . $phpStr . '?>');

$renderer = include( './cache/cache_' . $cacheName . '.php' );

$data = array(
  'test' => 'TEST'
);

echo $renderer( $data );
```
Same error still persist:

```log
==> /var/log/httpd/ssl_error_log <==
[Tue Jun 18 16:21:24.023740 2019] [:error] [pid 15300] [client 79.173.173.4:62769] PHP Fatal error:  Uncaught exception 'Exception' with message 'Can not find partial for 'header', you should provide partials or partialresolver in options' in /home/www/lnc/src/LightnCandy.php:113\nStack trace:\n#0 /home/www/lnc/src/LightnCandy.php(55): LightnCandy\\LightnCandy::handleError(Array)\n#1 /home/www/lnc/index.php(22): LightnCandy\\LightnCandy::compile('{{> header }}\\r\\n...', Array)\n#2 {main}\n  thrown in /home/www/lnc/src/LightnCandy.php on line 113
```
When I remove `{{> header }}` from main.hbs it all works, I would expect that the partials will work same way as in handlebars and mustache?

Many thanks for any help.
Peter.

**Comment by zordius** [comment]
for lightncandy 0.23 partials should be provided by code but not another file, please read document here: https://github.com/zordius/lightncandy/tree/v0.23#partial-support , and do the file loading task yourself.

**Comment by flavi1** [comment]
Hello.

My problem is the same, but in a more specific context.
I need to parse each individual template before compilation and push the filename in a custom debug stack array during runtime.

I don't want to modify any lightncandy file. (easy updates, bigger code time life).

I will try to extends the LightnCandy main class to override compile and compilePartial methods.

By design, the first parameter of theses methods is directly the template string.
I need it to be a filename, then i will just wrote a new method getTemplateFromFile to resolve the problem.

I hope this won't enter in conflict with any part of lightncandy library, and this can be an helpful idea for anyone.

Thanks

**Comment by flavi1** [comment]
Oops.
First problem : LightnCandy::compilePartial doesn't seem to be used anywhere. Any suggestion?

**Comment by flavi1** [comment]
Compiler::partial() method use Partial::compileStatic().
Partial::compileStatic() method use Compiler::compileTemplate().
I will not be able to do what i want without modify anything since it seem to be a closed loop in a lower level than the main LightnCandy class...

Would you like me to post a new feature ticket, or it's ok with this one?

**Comment by zordius** [comment]
Do you mean to use v0.23 ? Or current version?
